-- Add new audit action types for waitlist and upgrade operations
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'WAITLIST_CREATED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'WAITLIST_CANCELLED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'WAITLIST_OFFERED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'WAITLIST_COMPLETED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'UPGRADE_STARTED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'UPGRADE_PAID';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'UPGRADE_COMPLETED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'FINAL_EXTENSION_STARTED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'FINAL_EXTENSION_PAID';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'FINAL_EXTENSION_COMPLETED';








