-- Add REGISTER_SIGN_IN, REGISTER_SIGN_OUT, and REGISTER_FORCE_SIGN_OUT to audit_action enum

ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'REGISTER_SIGN_IN';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'REGISTER_SIGN_OUT';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'REGISTER_FORCE_SIGN_OUT';






